language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip3 install -r requirements.txt
  - pip3 install flake8

script:
  - python setup.py sdist
  - pip install dist/*.tar.gz
  - pytest
  - flake8 supersuit/ --ignore E501,E402,F401
  - flake8 test/ --ignore E501,E402,F401,F841
